# Generated by Django 4.1.2 on 2022-10-21 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=3)),
                ('number', models.CharField(max_length=4)),
                ('barcode', models.ImageField(upload_to='')),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='inv_mgmt_app.box')),
                ('current_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_mgmt_app.location')),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv_mgmt_app.denomination')),
            ],
        ),
        migrations.CreateModel(
            name='Box_Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_date', models.DateField()),
                ('sent_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_sent', to='inv_mgmt_app.location')),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments_received', to='inv_mgmt_app.location')),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='box_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='inv_mgmt_app.box_container'),
        ),
    ]
