# Generated by Django 4.1.2 on 2022-10-27 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Box",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("box_number", models.CharField(max_length=50)),
                ("series_from", models.CharField(max_length=3)),
                ("series_to", models.CharField(max_length=3)),
                ("serial_number_from", models.CharField(max_length=7)),
                ("serial_number_to", models.CharField(max_length=7)),
                ("packing_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="BoxType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("number_of_bundles", models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Denomination",
            fields=[
                (
                    "code",
                    models.CharField(max_length=2, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("value", models.PositiveIntegerField()),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="SubLocation",
            fields=[
                (
                    "code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=50)),
                ("active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Bundle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bundle_number_in_box", models.CharField(max_length=2)),
                (
                    "box",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bundles",
                        to="inv_mgmt_app.box",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BoxContainer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shipment_date", models.DateField()),
                ("boxes", models.ManyToManyField(to="inv_mgmt_app.box")),
                (
                    "sent_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments_sent",
                        to="inv_mgmt_app.location",
                    ),
                ),
                (
                    "sent_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments_received",
                        to="inv_mgmt_app.location",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="box",
            name="box_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inv_mgmt_app.boxtype"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="current_location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inv_mgmt_app.location"
            ),
        ),
        migrations.AddField(
            model_name="box",
            name="denomination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inv_mgmt_app.denomination",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="box",
            unique_together={
                ("denomination", "series_from", "serial_number_to"),
                ("denomination", "series_from", "serial_number_from"),
                ("box_number", "packing_date"),
            },
        ),
    ]
